#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
# aws cloudformation create-stack --stack-name $stack --template-body file://policy.yaml --capabilities CAPABILITY_IAM

---

AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates a policy, a role and a user to install OCP

Resources:

  Group:
    DependsOn:
    - PolicyDelete
    - PolicyDeleteNetwork
    - PolicyEC2install
    - PolicyEC2network
    - PolicyELB
    - PolicyIAM
    - PolicyManifest
    - PolicyRoute53
    - PolicyS3install
    - PolicyS3operator
    Properties:
      ManagedPolicyArns:
      - !Ref PolicyDelete
      - !Ref PolicyDeleteNetwork
      - !Ref PolicyEC2install
      - !Ref PolicyEC2network
      - !Ref PolicyELB
      - !Ref PolicyIAM
      - !Ref PolicyManifest
      - !Ref PolicyRoute53
      - !Ref PolicyS3install
      - !Ref PolicyS3operator
    Type: AWS::IAM::Group

# Required EC2 permissions for installation
  PolicyEC2install:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - ec2:AuthorizeSecurityGroupEgress
          - ec2:AuthorizeSecurityGroupIngress
          - ec2:CreateNetworkInterface
          - ec2:CreateSecurityGroup
          - ec2:CreateTags
          - ec2:CreateVolume
          - ec2:DeleteSecurityGroup
          - ec2:DeleteSnapshot
          - ec2:RevokeSecurityGroupEgress
          - ec2:RevokeSecurityGroupIngress
          - ec2:RunInstances
          - ec2:TerminateInstances
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - ec2:AllocateAddress
          - ec2:AssociateAddress
          - ec2:CopyImage
          - ec2:AttachNetworkInterface
          - ec2:DeregisterImage
          - ec2:DescribeAccountAttributes
          - ec2:DescribeAddresses
          - ec2:DescribeAvailabilityZones
          - ec2:DescribeDhcpOptions
          - ec2:DescribeImages
          - ec2:DescribeInstanceAttribute
          - ec2:DescribeInstanceCreditSpecifications
          - ec2:DescribeInstances
          - ec2:DescribeInternetGateways
          - ec2:DescribeKeyPairs
          - ec2:DescribeNatGateways
          - ec2:DescribeNetworkAcls
          - ec2:DescribeNetworkInterfaces
          - ec2:DescribePrefixLists
          - ec2:DescribeRegions
          - ec2:DescribeRouteTables
          - ec2:DescribeSecurityGroups
          - ec2:DescribeSubnets
          - ec2:DescribeTags
          - ec2:DescribeVolumes
          - ec2:DescribeVpcAttribute
          - ec2:DescribeVpcClassicLink
          - ec2:DescribeVpcClassicLinkDnsSupport
          - ec2:DescribeVpcEndpoints
          - ec2:DescribeVpcs
          - ec2:GetEbsDefaultKmsKeyId
          - ec2:ModifyInstanceAttribute
          - ec2:ModifyNetworkInterfaceAttribute
          - ec2:ReleaseAddress
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# If you use an existing VPC, your account does not require these permissions for creating network resources
# Required permissions for creating network resources during installation
  PolicyEC2network:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - "lambda:CreateFunction"
          - "lambda:GetFunction"
          - "lambda:GetFunctionConfiguration"
          - "lambda:InvokeFunction"
          - "lambda:ListFunctions"
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - "ec2:CreateDhcpOptions"
          - "ec2:CreateInternetGateway"
          - "ec2:CreateNatGateway"
          - "ec2:CreateRoute"
          - "ec2:CreateSubnet"          
          - "ec2:CreateVpc"
          - "ec2:CreateVpcEndpoint"
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - "ec2:AssociateDhcpOptions"
          - "ec2:CreateRouteTable"
          - "ec2:AttachInternetGateway"
          - "ec2:ModifyVpcAttribute"
          - "ec2:AssociateRouteTable"
          - "ec2:ModifySubnetAttribute"
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# Required Elasticloadbalancing permissions for installation
  PolicyELB:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - elasticloadbalancing:AddTags
          - elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
          - elasticloadbalancing:AttachLoadBalancerToSubnets
          - elasticloadbalancing:ConfigureHealthCheck
          - elasticloadbalancing:CreateLoadBalancer
          - elasticloadbalancing:CreateLoadBalancerListeners
          - elasticloadbalancing:DeleteLoadBalancer
          - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
          - elasticloadbalancing:ModifyLoadBalancerAttributes
          - elasticloadbalancing:RegisterInstancesWithLoadBalancer
          - elasticloadbalancing:SetLoadBalancerPoliciesOfListener
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - elasticloadbalancing:DescribeInstanceHealth
          - elasticloadbalancing:DescribeListeners
          - elasticloadbalancing:DescribeLoadBalancerAttributes
          - elasticloadbalancing:DescribeLoadBalancers
          - elasticloadbalancing:DescribeTags
          - elasticloadbalancing:DescribeTargetGroupAttributes
          - elasticloadbalancing:DescribeTargetHealth
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - elasticloadbalancing:CreateListener
          - elasticloadbalancing:CreateTargetGroup
          - elasticloadbalancing:DeregisterTargets
          - elasticloadbalancing:ModifyTargetGroup
          - elasticloadbalancing:ModifyTargetGroupAttributes
          - elasticloadbalancing:RegisterTargets
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# Required IAM permissions for installation
  PolicyIAM:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - iam:AddRoleToInstanceProfile
          - iam:CreateInstanceProfile
          - iam:CreateRole
          - iam:DeleteInstanceProfile
          - iam:DeleteRole
          - iam:DeleteRolePolicy
          - iam:GetInstanceProfile
          - iam:GetRole
          - iam:GetRolePolicy
          - iam:GetUser
          - iam:ListInstanceProfilesForRole
          - iam:PassRole
          - iam:PutRolePolicy
          - iam:RemoveRoleFromInstanceProfile
          - iam:SimulatePrincipalPolicy
          - iam:TagRole
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - iam:ListRoles
          - iam:ListUsers
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# Required Route53 permissions for installation
  PolicyRoute53:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - route53:ChangeResourceRecordSets
          - route53:ChangeTagsForResource
          - route53:DeleteHostedZone
          - route53:GetChange
          - route53:GetHostedZone
          - route53:ListResourceRecordSets
          - route53:ListTagsForResource
          - route53:UpdateHostedZoneComment
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - route53:CreateHostedZone
          - route53:ListHostedZones
          - route53:ListHostedZonesByName
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# Required S3 permissions for installation
  PolicyS3install:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - s3:CreateBucket
          - s3:DeleteBucket
          - s3:GetAccelerateConfiguration
          - s3:GetBucketAcl
          - s3:GetBucketCors
          - s3:GetBucketLocation
          - s3:GetBucketLogging
          - s3:GetBucketObjectLockConfiguration
          - s3:GetBucketReplication
          - s3:GetBucketRequestPayment
          - s3:GetBucketTagging
          - s3:GetBucketVersioning
          - s3:GetBucketWebsite
          - s3:GetEncryptionConfiguration
          - s3:GetLifecycleConfiguration
          - s3:GetReplicationConfiguration
          - s3:ListBucket
          - s3:PutBucketAcl
          - s3:PutBucketTagging
          - s3:PutEncryptionConfiguration
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# S3 permissions that cluster Operators require
  PolicyS3operator:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - s3:DeleteObject
          - s3:GetObject
          - s3:GetObjectAcl
          - s3:GetObjectTagging
          - s3:GetObjectVersion
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:PutObjectTagging
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# Required permissions to delete base cluster resources
  PolicyDelete:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - ec2:DeleteVolume
          - elasticloadbalancing:DeleteTargetGroup
          - iam:DeleteAccessKey
          - iam:DeleteUser
          - iam:ListInstanceProfiles
          - iam:ListRolePolicies
          - iam:ListUserPolicies
          - s3:ListBucketVersions
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - autoscaling:DescribeAutoScalingGroups
          - ec2:DeleteNetworkInterface
          - elasticloadbalancing:DescribeTargetGroups
          - tag:GetResources
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - s3:DeleteObject
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# If you use an existing VPC, your account does not require these permissions for deleting network resources
# Required permissions to delete network resources
  PolicyDeleteNetwork:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - "lambda:DeleteFunction"
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - ec2:DeleteDhcpOptions
          - ec2:DeleteInternetGateway
          - ec2:DeleteRoute
          - ec2:DeleteRouteTable
          - ec2:DeleteVpcEndpoints
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - ec2:DeleteNatGateway
          - ec2:DeleteSubnet
          - ec2:DeleteVpc
          - ec2:DetachInternetGateway
          - ec2:DisassociateRouteTable
          - ec2:ReplaceRouteTableAssociation
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

# Additional IAM and S3 permissions that are required to create manifests
  PolicyManifest:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - cloudformation:CreateStack
          - cloudformation:DeleteStack
          - cloudformation:DescribeStacks
          - cloudformation:ListStacks
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - iam:CreateAccessKey
          - iam:CreateUser
          - iam:DeleteAccessKey
          - iam:DeleteUser
          - iam:DeleteUserPolicy
          - iam:GetUserPolicy
          - iam:ListAccessKeys
          - iam:PutUserPolicy
          - iam:TagUser
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - s3:GetBucketPublicAccessBlock
          - s3:ListBucketMultipartUploads
          - s3:PutBucketPublicAccessBlock
          - s3:PutLifecycleConfiguration
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - s3:AbortMultipartUpload
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - s3:HeadBucket
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

  User:
    DependsOn: Group
    Properties:
      Groups:
      - !Ref Group
    Type: AWS::IAM::User

