apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: CLUSTER_NAME-CLUSTER_ID-ROLE-ZONE
  namespace: openshift-machine-api
  finalizers:
    - machine.machine.openshift.io
  labels:
    machine.openshift.io/cluster-api-cluster: CLUSTER_NAME-CLUSTER_ID
    machine.openshift.io/cluster-api-machine-role: ROLE
    machine.openshift.io/cluster-api-machine-type: ROLE
    machine.openshift.io/instance-type: INSTANCE_TYPE
    machine.openshift.io/region: REGION
    machine.openshift.io/zone: ZONE
spec:
  providerSpec:
    value:
      userDataSecret:
        name: master-user-data
      placement:
        availabilityZone: ZONE
        region: REGION
      credentialsSecret:
        name: aws-cloud-credentials
      instanceType: INSTANCE_TYPE
      blockDevices:
        - ebs:
            encrypted: true
            iops: 0
            kmsKey:
              arn: ''
            volumeSize: VOLUME_SIZE
            volumeType: VOLUME_TYPE
      securityGroups:
        - filters:
            - name: 'tag:Name'
              values:
                - CLUSTER_NAME-CLUSTER_ID-ROLE-sg
      kind: AWSMachineProviderConfig
      loadBalancers:
        - name: CLUSTER_NAME-CLUSTER_ID-int
          type: network
        - name: CLUSTER_NAME-CLUSTER_ID-ext
          type: network
      tags:
        - name: kubernetes.io/cluster/CLUSTER_NAME-CLUSTER_ID
          value: owned
      deviceIndex: 0
      ami:
        id: ami-AMI_ID
      subnet:
        filters:
          - name: 'tag:Name'
            values:
              - CLUSTER_NAME-CLUSTER_ID-private-ZONE
      apiVersion: awsproviderconfig.openshift.io/v1beta1
      iamInstanceProfile:
        id: CLUSTER_NAME-CLUSTER_ID-ROLE-profile
